---
version: '2.0'
services:

    sut:
        build: .
        command: sh -c "wait-for-it couch_avatars:5984 && wait-for-it redis_auth:6379 && curl -X PUT -H Accept:text/plain http://couch_avatars:5984/ganomede_avatars_test && npm test"
        volumes:
        - ./wait-for-it:/usr/local/bin/wait-for-it
        links:
        - couch:couch_avatars
        - redis:redis_auth

    couch:
        image: klaemo/couchdb:1.6.1

    redis:
        image: redis:alpine
