app:
    build: .
    command: node index.js
    volumes:
     - ./src:/home/app/code/src
     - ./tests:/home/app/code/tests
     - ./doc:/home/app/code/doc
     - ./Makefile:/home/app/code/Makefile
     - ./index.js:/home/app/code/index.js
     - ./config.js:/home/app/code/config.js
     - ./package.json:/home/app/code/package.json
    ports:
     - "8000:8000"
    links:
     - couch:couch_avatars
     - redis:redis_auth

couch:
    image: klaemo/couchdb:1.6.1

redis:
    image: redis:alpine
